class Constants:
    STRUCTURE_STEPS = {
        "blog": [
            "Introduction",
            "Main Content",
            "Conclusion",
            "FAQs",
            "Meta Description",
            "References",
        ],
        "how-to": [
            "Introduction",
            "Step-by-Step Guide",
            "Tips & Best Practices",
            "Conclusion",
            "FAQs",
            "Meta Description",
            "References",
        ],
        "listicle": [
            "Introduction",
            "List Items with Details",
            "Conclusion",
            "FAQs",
            "Meta Description",
            "References",
        ],
        "comparison": [
            "Introduction",
            "Criteria for Comparison",
            "Detailed Comparison",
            "Pros & Cons",
            "Conclusion",
            "FAQs",
            "Meta Description",
            "References",
        ],
        "guide": [
            "Introduction",
            "Detailed Guide Sections",
            "Expert Tips",
            "Conclusion",
            "FAQs",
            "Meta Description",
            "References",
        ],
        "faq": [
            "Introduction",
            "Comprehensive FAQ Section",
            "Conclusion",
            "Meta Description",
            "References",
        ],
    }
